# Generated by Django 3.1.5 on 2021-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_id',
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
